name: Build and Run Tests

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master", "CI" ]

jobs:

  # Build waterbox and cores
  build-waterbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      #with:
      #  submodules: recursive
    - name: Getting musl
      run: git submodule init waterbox/musl;
           git submodule update waterbox/musl
    - name: Building musl
      working-directory: ./waterbox/musl
      env:
        CC: clang
        CXX: clang++
      run: ./wbox_configure.sh;
           ./wbox_build.sh;